# Generated by Django 4.0.4 on 2022-06-22 21:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('wanted_position', models.CharField(max_length=200)),
                ('wanted_city', models.CharField(max_length=200)),
                ('applie_date', models.DateField(default=django.utils.timezone.now)),
                ('mobile_number', models.CharField(default='000000000', max_length=30)),
                ('color', models.CharField(default='#FFFFFF', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='testing', max_length=400)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='applicants.applicant')),
            ],
        ),
    ]
